[package]
name = "lf-gfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { version = "0.16" }
wgpu-async = { path = "../wgpu-async" }
wgpu-lazybuffers = { path = "../wgpu-lazybuffers" }
winit = { version = "0.27", features = ["serde"] }
async-trait = "0.1"
bytemuck = "1.12"
bytemuck_derive = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bitflags = "2.0"
tokio = { version = "1.0", features = ["rt"] }
