[package]
name = "lf-gfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { version = "0.14" }
async-trait = "0.1"
bytemuck = "1.12"
bytemuck_derive = "1.3"
