[package]
name = "lf-gfx"
version = "0.0.1"
edition = "2021"

[dependencies]
wgpu = { version = "0.17" }
winit = { version = "0.28", features = ["serde"] }
async-trait = "0.1"
bytemuck = "1.12"
bytemuck_derive = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bitflags = "2.0"
pollster = "0.3.0"
thiserror = "1.0"
flume = "0.10"